/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.core.dto.BatchDTO;
import edu.ijse.gdse43.core.dto.RegistrationDTO;
import edu.ijse.gdse43.core.dto.RegistrationDetailsDTO;
import edu.ijse.gdse43.core.dto.StudentDTO;
import edu.ijse.gdse43.core.dto.SubjectDTO;
import edu.ijse.gdse43.custom.controller.BatchController;
import edu.ijse.gdse43.custom.controller.StudentController;
import edu.ijse.gdse43.custom.controller.SubjectController;
import edu.ijse.gdse43.util.Validation;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
//@Report("edu.ijse.Jasper")
public class AddRegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form AddRegistrationForm
     */
    public AddRegistrationForm() {
        initComponents();
        loadIds();
        loadSystemDate();
        loadBatchIDs();
        txtStudentID.setEditable(false);
        txtRegistrationID.setEditable(false);
        txtRDate.setEditable(false);
        loadSubjectIds();
        txtFName.requestFocusInWindow();
        lblFormat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        AddStudentPanel = new javax.swing.JPanel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtSchool = new javax.swing.JTextField();
        txtFees = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXLabel19 = new org.jdesktop.swingx.JXLabel();
        jXLabel20 = new org.jdesktop.swingx.JXLabel();
        txtLName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jXLabel21 = new org.jdesktop.swingx.JXLabel();
        txtStudentID = new javax.swing.JTextField();
        jXLabel24 = new org.jdesktop.swingx.JXLabel();
        jXLabel25 = new org.jdesktop.swingx.JXLabel();
        txtRegistrationID = new javax.swing.JTextField();
        txtRDate = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jXLabel23 = new org.jdesktop.swingx.JXLabel();
        BatchIDComboBox = new javax.swing.JComboBox();
        SubjectIdComboBox = new javax.swing.JComboBox();
        lblFormat = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        AddStudentPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel12.setText("Name of the School");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, 25));

        jXLabel1.setBackground(new java.awt.Color(255, 153, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255)));
        jXLabel1.setText("                                        ADD  REGISTRATION");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddStudentPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));

        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 490, -1));

        txtFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeesActionPerformed(evt);
            }
        });
        txtFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFeesKeyReleased(evt);
            }
        });
        AddStudentPanel.add(txtFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 120, -1));

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFNameKeyReleased(evt);
            }
        });
        AddStudentPanel.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 230, -1));

        jXLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel13.setText("Fees");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 113, 25));

        jXLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel14.setText("First Name");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 113, 25));

        jXLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel15.setText("Subject");
        jXLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 113, 25));

        jXLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel16.setText("Last Name");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 113, 25));

        jXLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel17.setText("Date of Birth");
        jXLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 113, 25));

        jXLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel18.setText("Phone");
        jXLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 113, 25));

        jXLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel19.setText("Address");
        jXLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 113, 25));

        jXLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel20.setText("National ID");
        jXLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 113, 25));

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLNameKeyReleased(evt);
            }
        });
        AddStudentPanel.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, -1));

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 230, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        AddStudentPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 490, -1));

        txtNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIDActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 230, -1));
        AddStudentPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 382, 910, 20));

        jXLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel21.setText("Student ID");
        jXLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 113, 25));

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 120, -1));

        jXLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel24.setText("Registration ID");
        jXLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 113, 25));

        jXLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel25.setText("Registration Date");
        jXLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 113, 25));

        txtRegistrationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrationIDActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtRegistrationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 120, -1));

        txtRDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRDateActionPerformed(evt);
            }
        });
        AddStudentPanel.add(txtRDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 120, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        AddStudentPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 100, 40));

        btnAdd.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        AddStudentPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 100, 40));

        jXLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel23.setText("Batch Name");
        jXLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 113, 25));

        BatchIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BatchIDComboBoxItemStateChanged(evt);
            }
        });
        AddStudentPanel.add(BatchIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 160, 30));

        AddStudentPanel.add(SubjectIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 150, 30));

        lblFormat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFormat.setText("yyyy-MM-dd");
        AddStudentPanel.add(lblFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            txtFName.setText("");
            txtLName.setText("");
            txtDOB.setText("");
            txtPhone.setText("");
            txtAddress.setText("");
            txtNID.setText("");
            txtSchool.setText("");
            txtRegistrationID.setText("");
            txtRDate.setText("");
            txtFees.setText("");
            BatchIDComboBox.setSelectedItem("");
            txtFName.requestFocus();
        } else if (response == 1) {

        } else if (response == 2) {

        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {
            String subject=SubjectIdComboBox.getSelectedItem().toString();
            SubjectDTO searchSubjectName = SubjectController.searchSubjectName(subject);
            StudentDTO student = new StudentDTO(
                    txtStudentID.getText(),
                    txtRegistrationID.getText(),
                    txtFName.getText(),
                    txtLName.getText(),
                    txtDOB.getText(),
                    txtPhone.getText(),
                    txtAddress.getText(),
                    txtNID.getText(),
                    txtSchool.getText());
            RegistrationDTO registration = new RegistrationDTO(
                    txtRegistrationID.getText(),
                    txtRDate.getText(),
                    txtFees.getText(), (String) BatchIDComboBox.getSelectedItem());
            RegistrationDetailsDTO registrationDetails=new RegistrationDetailsDTO(
            txtRegistrationID.getText(), 
            searchSubjectName.getSubjectID());

            boolean result = StudentController.addStudentDetails(student, registration,registrationDetails);

            String FName = txtFName.getText();

            if (FName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Student name");
                txtFName.selectAll();
                txtFName.requestFocusInWindow();
                return;
            }
            String LName = txtFName.getText();
            if (LName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Student name");
                txtLName.selectAll();
                txtLName.requestFocusInWindow();
                return;
            }

            String dob = txtDOB.getText();
            if (LName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a DOB");
                txtDOB.selectAll();
                txtDOB.requestFocusInWindow();
                return;
            }

            String Phone = txtPhone.getText();
            if (Phone.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Phone number");
                txtPhone.selectAll();
                txtPhone.requestFocusInWindow();
                return;
            }
            String Address = txtAddress.getText();

            if (Address.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Address");
                txtAddress.selectAll();
                txtAddress.requestFocusInWindow();
                return;
            }
            String NID = txtNID.getText();

            if (NID.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a NIC");
                txtNID.selectAll();
                txtNID.requestFocusInWindow();
                return;
            }
            String School = txtSchool.getText();

            if (School.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a School");
                txtSchool.selectAll();
                txtSchool.requestFocusInWindow();
                return;
            }

            String Registration = txtRegistrationID.getText();

            if (Registration.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Registration");
                txtRegistrationID.selectAll();
                txtRegistrationID.requestFocusInWindow();
                return;
            }

            String RDate = txtRDate.getText();

            if (Address.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Date");
                txtRDate.selectAll();
                txtRDate.requestFocusInWindow();
                return;
            }

            String Fees = txtFees.getText();

            if (Fees.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Fees");
                txtFees.selectAll();
                txtFees.requestFocusInWindow();
                return;
            }

            JOptionPane.showMessageDialog(this, "Student has been successfully Added");
            txtStudentID.setText("");
             txtFName.setText("");
             txtLName.setText("");
             txtDOB.setText("");
             txtPhone.setText("");
             txtAddress.setText("");
             txtNID.setText("");
             txtSchool.setText("");
             txtRegistrationID.setText("");
             txtRDate.setText("");
             txtFees.setText("");
             BatchIDComboBox.setSelectedItem("");
            txtStudentID.setText(IdGenarator.getNewID("Student", "StudentID", "S"));
            txtRegistrationID.setText(IdGenarator.getNewID("Registration", "RegistrationID", "R"));
            txtFName.requestFocus();
        } catch (IOException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        txtFName.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        txtLName.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        txtDOB.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        txtPhone.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
       
        txtAddress.requestFocus();  
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtNID.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIDActionPerformed
        txtSchool.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIDActionPerformed

    private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
        txtFees.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolActionPerformed

    private void txtRDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRDateActionPerformed
        txtFees.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtRDateActionPerformed

    private void txtRegistrationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrationIDActionPerformed
        txtRDate.requestFocus();      // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrationIDActionPerformed

    private void txtFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeesActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_txtFeesActionPerformed

    private void txtFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyReleased
        Validation.name(txtFName);
    }//GEN-LAST:event_txtFNameKeyReleased

    private void txtLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyReleased
        Validation.name(txtLName);
    }//GEN-LAST:event_txtLNameKeyReleased

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
Validation.phoneNumber(txtPhone);        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtFeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFeesKeyReleased
Validation.phoneNumber(txtFees);        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeesKeyReleased

    private void BatchIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BatchIDComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BatchIDComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JComboBox BatchIDComboBox;
    private javax.swing.JComboBox SubjectIdComboBox;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel19;
    private org.jdesktop.swingx.JXLabel jXLabel20;
    private org.jdesktop.swingx.JXLabel jXLabel21;
    private org.jdesktop.swingx.JXLabel jXLabel23;
    private org.jdesktop.swingx.JXLabel jXLabel24;
    private org.jdesktop.swingx.JXLabel jXLabel25;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFees;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRDate;
    public static javax.swing.JTextField txtRegistrationID;
    private javax.swing.JTextField txtSchool;
    public static javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables

    private void loadIds() {
        try {
            txtStudentID.setText(IdGenarator.getNewID("Student", "StudentID", "S"));
            txtRegistrationID.setText(IdGenarator.getNewID("Registration", "RegistrationID", "R"));
        } catch (IOException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String FormatDate = df.format(d1);
        txtRDate.setText(FormatDate);
    }

    private void loadBatchIDs() {
        try {
            ArrayList<BatchDTO> batchList = BatchController.getAllBatches();
            for (BatchDTO batchId : batchList) {
                BatchIDComboBox.addItem(batchId.getBatchID());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadSubjectIds() {
        try {
            ArrayList<SubjectDTO>subjectList=SubjectController.getAllSubjects();
            for (SubjectDTO subjectId : subjectList) {
                SubjectIdComboBox.addItem(subjectId.getSubjectName());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(AddRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
