/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.gdse43.custom.controller.TeacherController;
import edu.ijse.gdse43.core.dto.TeacherDTO;
import edu.ijse.gdse43.util.Validation;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class DeleteTeacherForm extends javax.swing.JPanel {

    /**
     * Creates new form DeleteTeacherForm
     */
    public DeleteTeacherForm() throws ClassNotFoundException, SQLException, Exception {
        initComponents();
        loadTeacherIds();
        txtTeacherName.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtNID.setText("");
        txtSubject.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSubjectId = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel22 = new org.jdesktop.swingx.JXLabel();
        jXLabel23 = new org.jdesktop.swingx.JXLabel();
        jXLabel24 = new org.jdesktop.swingx.JXLabel();
        jXLabel25 = new org.jdesktop.swingx.JXLabel();
        jXLabel26 = new org.jdesktop.swingx.JXLabel();
        jXLabel28 = new org.jdesktop.swingx.JXLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        teacherIdComboBox = new javax.swing.JComboBox();
        txtSubject = new javax.swing.JTextField();

        txtSubjectId.setBackground(new java.awt.Color(255, 255, 255));
        txtSubjectId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jXLabel1.setText("                               REMOVE  TEACHER");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSubjectId.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));

        jXLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel22.setText("Teacher Name");
        jXLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 113, 25));

        jXLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel23.setText("Address");
        jXLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 113, 25));

        jXLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel24.setText("Phone");
        jXLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 113, 25));

        jXLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel25.setText("National ID");
        jXLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 113, 25));

        jXLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel26.setText("Subject");
        jXLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 113, 25));

        jXLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel28.setText("Teacher ID");
        jXLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSubjectId.add(jXLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 113, 25));

        txtTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherNameActionPerformed(evt);
            }
        });
        txtTeacherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeacherNameKeyReleased(evt);
            }
        });
        txtSubjectId.add(txtTeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 400, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtSubjectId.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtSubjectId.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 520, -1));

        txtNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIDActionPerformed(evt);
            }
        });
        txtSubjectId.add(txtNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        txtSubjectId.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 100, 40));

        btnDelete.setBackground(new java.awt.Color(0, 0, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        txtSubjectId.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 100, 40));

        teacherIdComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teacherIdComboBoxItemStateChanged(evt);
            }
        });
        teacherIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherIdComboBoxActionPerformed(evt);
            }
        });
        txtSubjectId.add(teacherIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, 30));

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        txtSubjectId.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIDActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            txtTeacherName.setText("");
            txtPhone.setText("");
            txtAddress.setText("");
            txtNID.setText("");
            txtSubject.setText("");
            txtTeacherName.requestFocus();
        }else if(response==1){
            
        }else if(response==2){
            
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            TeacherDTO teacher = new TeacherDTO(
                    (String) teacherIdComboBox.getSelectedItem(),
                    txtTeacherName.getText(),
                    txtPhone.getText(),
                    txtAddress.getText(),
                    txtNID.getText(),
                    txtSubject.getText());
            boolean result = TeacherController.deleteTeacher(teacher);
            if (result) {
                JOptionPane.showMessageDialog(this, "Teacher has been successfully deleted");
            } else {
                JOptionPane.showMessageDialog(this, "Teacher hasn't been deleted");

            }
             txtTeacherName.setText("");
            txtPhone.setText("");
            txtAddress.setText("");
            txtNID.setText("");
            txtSubject.setText("");
            txtTeacherName.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(DeleteTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void teacherIdComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teacherIdComboBoxItemStateChanged

        try {
            String TeacherID = (String) teacherIdComboBox.getSelectedItem().toString();
            TeacherDTO teacher = null;
            teacher = TeacherController.searchTeacher(TeacherID);
            txtTeacherName.setText(teacher.getName());
            txtPhone.setText(teacher.getPhone());
            txtAddress.setText(teacher.getAddress());
            txtNID.setText(teacher.getNic());
            txtSubject.setText(teacher.getSubject());
            txtTeacherName.setEditable(false);
            txtPhone.setEditable(false);
            txtAddress.setEditable(false);
            txtNID.setEditable(false);
            txtSubject.setEditable(false);
            
           
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(DeleteTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_teacherIdComboBoxItemStateChanged

    private void teacherIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherIdComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherIdComboBoxActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void txtTeacherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeacherNameKeyReleased
        Validation.name(txtTeacherName);
    }//GEN-LAST:event_txtTeacherNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel22;
    private org.jdesktop.swingx.JXLabel jXLabel23;
    private org.jdesktop.swingx.JXLabel jXLabel24;
    private org.jdesktop.swingx.JXLabel jXLabel25;
    private org.jdesktop.swingx.JXLabel jXLabel26;
    private org.jdesktop.swingx.JXLabel jXLabel28;
    private javax.swing.JComboBox teacherIdComboBox;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtNID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JPanel txtSubjectId;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables

    private void loadTeacherIds() {
        try {
            ArrayList<TeacherDTO> TeacherList = TeacherController.getAllTeachers();
            for (TeacherDTO TeacherId : TeacherList) {
                teacherIdComboBox.addItem(TeacherId.getTeacherID());

            }
        } catch (Exception ex) {
            Logger.getLogger(DeleteTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
