/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.core.dto.RegistrationDTO;
import edu.ijse.gdse43.core.dto.StudentDTO;
import edu.ijse.gdse43.custom.controller.RegistrationController;
import edu.ijse.gdse43.custom.controller.StudentController;
import static edu.ijse.gdse43.view.AddRegistrationForm.txtRegistrationID;
import static edu.ijse.gdse43.view.AddRegistrationForm.txtStudentID;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class DeleteStudentForm extends javax.swing.JPanel {

    /**
     * Creates new form DeleteStudentForm
     */
    public DeleteStudentForm() {
        initComponents();
        loadStudentIds();
        loadRegistrationIds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNID = new javax.swing.JPanel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtSchool = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXLabel19 = new org.jdesktop.swingx.JXLabel();
        jXLabel20 = new org.jdesktop.swingx.JXLabel();
        txtLName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtBatchId = new javax.swing.JTextField();
        jXLabel21 = new org.jdesktop.swingx.JXLabel();
        jXLabel24 = new org.jdesktop.swingx.JXLabel();
        txtRegistrationID = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        StudentIDComboBox = new javax.swing.JComboBox();
        txtNIC = new javax.swing.JTextField();
        jXLabel22 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNID.setBackground(new java.awt.Color(255, 255, 255));
        txtNID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel12.setText("Name of the School");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, 25));

        jXLabel1.setBackground(new java.awt.Color(255, 153, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255)));
        jXLabel1.setText("                         REMOVE  STUDENT");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNID.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));
        txtNID.add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 490, -1));
        txtNID.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 230, -1));

        jXLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel14.setText("First Name");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 113, 25));

        jXLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel16.setText("Last Name");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 113, 25));

        jXLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel17.setText("Date of Birth");
        jXLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 113, 25));

        jXLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel18.setText("Phone");
        jXLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 113, 25));

        jXLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel19.setText("Batch Name");
        jXLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 113, 25));

        jXLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel20.setText("National ID");
        jXLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 113, 25));
        txtNID.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, -1));
        txtNID.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 230, -1));
        txtNID.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 230, -1));
        txtNID.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 490, -1));
        txtNID.add(txtBatchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 230, -1));

        jXLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel21.setText("Student ID");
        jXLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 113, 25));

        jXLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel24.setText("Registration ID");
        jXLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 113, 25));
        txtNID.add(txtRegistrationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        txtNID.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 100, 40));

        btnCancel.setBackground(new java.awt.Color(0, 0, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        txtNID.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 100, 40));

        StudentIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " " }));
        StudentIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StudentIDComboBoxItemStateChanged(evt);
            }
        });
        txtNID.add(StudentIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 220, 30));
        txtNID.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 230, -1));

        jXLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel22.setText("Address");
        jXLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNID.add(jXLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 113, 25));

        add(txtNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            StudentDTO student = new StudentDTO(
                    (String) StudentIDComboBox.getSelectedItem(),
                    txtRegistrationID.getText(),
                    txtFName.getText(),
                    txtLName.getText(),
                    txtDob.getText(),
                    txtPhone.getText(),
                    txtAddress.getText(),
                    txtNIC.getText(),
                    txtSchool.getText());
            boolean result = StudentController.deleteStudent(student);
            if (result) {
                JOptionPane.showMessageDialog(this, "Student has been successfully deleted");
            } else {
                JOptionPane.showMessageDialog(this, "Student hasn't been deleted");

            }
            txtRegistrationID.setText("");
                txtFName.setText("");
                txtLName.setText("");
                txtDob.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtBatchId.setText("");
                txtSchool.setText("");
                txtRegistrationID.setText("");
                txtBatchId.setText("");
                txtRegistrationID.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(DeleteStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
 int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            
                txtRegistrationID.setText("");
                txtFName.setText("");
                txtLName.setText("");
                txtDob.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtBatchId.setText("");
                txtSchool.setText("");
                txtRegistrationID.setText("");
                txtBatchId.setText("");
                txtRegistrationID.requestFocus();
           
        }else if(response==1){
            
        }else if(response==2){
            
        }
                                
    }//GEN-LAST:event_btnCancelActionPerformed

    private void StudentIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StudentIDComboBoxItemStateChanged
try {
            String StudentID = (String) StudentIDComboBox.getSelectedItem().toString();
            StudentDTO student = null;
            student = StudentController.searchTeacher(StudentID);
            txtRegistrationID.setText(student.getRegistrationID());
            txtFName.setText(student.getFrstName());
            txtLName.setText(student.getLastName());
            txtDob.setText(student.getDob());
            txtPhone.setText(student.getPhone());
            txtAddress.setText(student.getAddress());
            txtBatchId.setText(student.getNic());
            txtSchool.setText(student.getSchool());
        } catch (Exception ex) {
            Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StudentIDComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox StudentIDComboBox;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel19;
    private org.jdesktop.swingx.JXLabel jXLabel20;
    private org.jdesktop.swingx.JXLabel jXLabel21;
    private org.jdesktop.swingx.JXLabel jXLabel22;
    private org.jdesktop.swingx.JXLabel jXLabel24;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBatchId;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JPanel txtNID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRegistrationID;
    private javax.swing.JTextField txtSchool;
    // End of variables declaration//GEN-END:variables

    private void loadStudentIds() {
        try {
            ArrayList<StudentDTO> studentList = StudentController.getAllStudents();
            for (StudentDTO studentId : studentList) {
                StudentIDComboBox.addItem(studentId.getStudentID());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(DeleteStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadRegistrationIds() {
        try {
            ArrayList<StudentDTO> studentList = StudentController.getAllStudents();
            for (StudentDTO studentId : studentList) {
                StudentIDComboBox.addItem(studentId.getStudentID());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(DeleteStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
