/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.SimpleTimeZone;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author DEll
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        loadSystemDate();
        loadSystemTime();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        TitleLabel = new org.jdesktop.swingx.JXLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnPayment = new javax.swing.JButton();
        btnShedule = new javax.swing.JButton();
        btnExam = new javax.swing.JButton();
        btnBatc = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time");
        ButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Apps-session-logout-icon.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        btnSettings.setBackground(new java.awt.Color(102, 102, 102));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Services_48px.png"))); // NOI18N
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 60));

        btnReports.setBackground(new java.awt.Color(51, 255, 204));
        btnReports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Button-Previous-icon.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 80, 80));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 760));

        TitleLabel.setBackground(new java.awt.Color(0, 0, 153));
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/if_graduated_44907.png"))); // NOI18N
        TitleLabel.setText("          RASANYA  INSTITUTE");
        TitleLabel.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        TitleLabel.setOpaque(true);

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 130));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPayment.setBackground(new java.awt.Color(51, 51, 255));
        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Money-icon (1).png"))); // NOI18N
        btnPayment.setText("PAYMENT");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 280, 120));

        btnShedule.setBackground(new java.awt.Color(51, 51, 255));
        btnShedule.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/calendar-icon.png"))); // NOI18N
        btnShedule.setText("SCHEDULE");
        btnShedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSheduleActionPerformed(evt);
            }
        });
        jPanel1.add(btnShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 280, 120));

        btnExam.setBackground(new java.awt.Color(51, 51, 255));
        btnExam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit-file-icon.png"))); // NOI18N
        btnExam.setText("EXAM");
        btnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamActionPerformed(evt);
            }
        });
        jPanel1.add(btnExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 280, 120));

        btnBatc.setBackground(new java.awt.Color(51, 51, 255));
        btnBatc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBatc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/User-Group-icon.png"))); // NOI18N
        btnBatc.setText("BATCH");
        btnBatc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatcActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 280, 120));

        btnRegistration.setBackground(new java.awt.Color(51, 51, 255));
        btnRegistration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Graduate-female-icon (1).png"))); // NOI18N
        btnRegistration.setText("REGISTRATION");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, 120));

        btnTeacher.setBackground(new java.awt.Color(51, 51, 255));
        btnTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Teacher-male-icon.png"))); // NOI18N
        btnTeacher.setText("TEACHER");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(btnTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 280, 120));

        mainPanel.add(jPanel1);

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 910, 570));

        setSize(new java.awt.Dimension(1100, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnBatcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatcActionPerformed
        new BatchForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBatcActionPerformed

    private void btnSheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSheduleActionPerformed
        try {
            new ScheduleForm().setVisible(true);
            this.setVisible(false);// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSheduleActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        new TeacherForm().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamActionPerformed
        new ExamForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExamActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        new RegistrationForm().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        try {
            new PaymentForm().setVisible(true);
            this.setVisible(false);
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
new AccountSettings().setVisible(true);

    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
       
      Reports r = new Reports();
            mainPanel.removeAll();
            mainPanel.add(r);
            mainPanel.repaint();
            mainPanel.revalidate();
            mainPanel.setVisible(true);
       
    }//GEN-LAST:event_btnReportsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            new Reports().setVisible(false);
        jPanel1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private org.jdesktop.swingx.JXLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnBatc;
    private javax.swing.JButton btnExam;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnShedule;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FormatDate = df.format(d1);
        txtDate.setText(FormatDate);
    }

    private void loadSystemTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String FormatDate = df.format(d1);
                txtTime.setText(FormatDate);
            }
             }).start();
     
     
        
        
    }
}
