/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.core.dto.PaymentDTO;
import edu.ijse.gdse43.core.dto.SubjectDTO;
import edu.ijse.gdse43.custom.controller.PaymentController;
import edu.ijse.gdse43.custom.controller.SubjectController;
import edu.ijse.gdse43.dao.db.DBConnection;
import edu.ijse.gdse43.util.Validation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DEll
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() throws Exception {
        initComponents();
        loadSystemDate();
        loadSystemTime();
        loadPaymentID();
        loadSubjects();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TitleLabel = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel28 = new org.jdesktop.swingx.JXLabel();
        jXLabel29 = new org.jdesktop.swingx.JXLabel();
        jXLabel31 = new org.jdesktop.swingx.JXLabel();
        jXLabel34 = new org.jdesktop.swingx.JXLabel();
        jXLabel35 = new org.jdesktop.swingx.JXLabel();
        txtAmount = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnAddPayment = new javax.swing.JButton();
        jXLabel33 = new org.jdesktop.swingx.JXLabel();
        SubjectComboBox = new javax.swing.JComboBox();
        jXLabel32 = new org.jdesktop.swingx.JXLabel();
        txtPaymentId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time");
        ButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home-icon.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 84, 85));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 800));

        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Actions-window-close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        TitlePanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 60, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TitlePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 10, 60, 60));

        TitleLabel.setBackground(new java.awt.Color(0, 0, 153));
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/if_graduated_44907.png"))); // NOI18N
        TitleLabel.setText("          RASANYA  INSTITUTE");
        TitleLabel.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        TitleLabel.setOpaque(true);
        TitlePanel.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 130));

        jXLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        jXLabel1.setText("                                            PAYMENTS");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXLabel1.setOpaque(true);
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 910, 90));

        jXLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel28.setText("Teacher ID");
        jXLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 113, 25));

        jXLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel29.setText("Teacher ID");
        jXLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 113, 25));

        jXLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel31.setText("Student ID");
        jXLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 113, 25));

        jXLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel34.setText("Month");
        jXLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 113, 25));

        jXLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel35.setText("Amount");
        jXLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 113, 25));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 170, 30));

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 170, 30));

        txtMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthActionPerformed(evt);
            }
        });
        txtMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMonthKeyReleased(evt);
            }
        });
        getContentPane().add(txtMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 170, 30));

        btnView.setBackground(new java.awt.Color(0, 0, 102));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnViewItemStateChanged(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, 100, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 910, -1));

        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject", "Class Name", "Month", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblPayment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 100));

        btnCancel.setBackground(new java.awt.Color(0, 0, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 700, 100, 40));

        btnAddPayment.setBackground(new java.awt.Color(0, 0, 102));
        btnAddPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPayment.setText("Add");
        btnAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 100, 40));

        jXLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel33.setText("Subject Name");
        jXLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 113, 25));

        getContentPane().add(SubjectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 170, 30));

        jXLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel32.setText("Payment ID");
        jXLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jXLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 113, 25));

        txtPaymentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaymentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 170, 30));

        setSize(new java.awt.Dimension(1100, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthActionPerformed
       txtAmount.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
       
        
        try {
            ArrayList<PaymentDTO> alPayments = PaymentController.getAllPayments();
            DefaultTableModel dtm=(DefaultTableModel)tblPayment.getModel();
            dtm.setRowCount(0);
            for (PaymentDTO payment : alPayments) {
                Object[] rowData = {payment.getPaymentID(),
                    payment.getStudentID(),
                    payment.getSubjectID(),
                    payment.getMonth(),
                    payment.getAmount(),
                };
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            
            txtStudentID.setText("");
            txtMonth.setText("");
            txtAmount.setText("");
            txtStudentID.requestFocus();
        }else if(response==1){
            
        }else if(response==2){
            
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPaymentActionPerformed
        try {
            PaymentDTO payment = new PaymentDTO(
                    txtPaymentId.getText(),
                    txtStudentID.getText(),
                    SubjectComboBox.getSelectedItem().toString(),
                    txtMonth.getText(),
                    Integer.parseInt(txtAmount.getText()));
            boolean result = PaymentController.addPayment(payment);
            if (result) {
                JOptionPane.showMessageDialog(this, "Payment has been sucessfully added");
            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been sucessfully added");
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtStudentID.setText("");
            txtMonth.setText("");
            txtAmount.setText("");
        

    }//GEN-LAST:event_btnAddPaymentActionPerformed

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void btnViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnViewItemStateChanged

        
        /* String TeacherID=(String) teacherIdComboBox.getSelectedItem().toString();
         TeacherDTO teacher=null;
         teacher=TeacherController.searchTeacher(TeacherID);
         txtTeacherName.setText(teacher.getName());
         txtPhone.setText(teacher.getPhone());
         txtAddress.setText(teacher.getAddress());
         txtNID.setText(teacher.getNic());
         txtSubject.setText(teacher.getSubject());
            */
         
    }//GEN-LAST:event_btnViewItemStateChanged

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        
    }//GEN-LAST:event_txtAmountKeyReleased

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int response=JOptionPane.showConfirmDialog(this,"Are you sure want to exit");
        if(response==0){
            System.exit(0);
        }else if(response==1){
        }else if(response==2){

        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPaymentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIdActionPerformed

    private void txtMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonthKeyReleased
        
    }//GEN-LAST:event_txtMonthKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PaymentForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JComboBox SubjectComboBox;
    private org.jdesktop.swingx.JXLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnAddPayment;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel28;
    private org.jdesktop.swingx.JXLabel jXLabel29;
    private org.jdesktop.swingx.JXLabel jXLabel31;
    private org.jdesktop.swingx.JXLabel jXLabel32;
    private org.jdesktop.swingx.JXLabel jXLabel33;
    private org.jdesktop.swingx.JXLabel jXLabel34;
    private org.jdesktop.swingx.JXLabel jXLabel35;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtPaymentId;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String FormatDate = df.format(d1);
        txtDate.setText(FormatDate);
         
        
    }
    
    private void loadSystemTime() {
        new Timer(0, new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String FormatDate = df.format(d1);
                txtTime.setText(FormatDate);
            }
        }).start();
    }

    private void loadPaymentID() {
        try {
            txtPaymentId.setText(IdGenarator.getNewID("Payment", "PaymentID", "P"));
        } catch (IOException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSubjects() throws Exception {
        try {
           ArrayList<SubjectDTO>subjectList=SubjectController.getAllSubjects();
            for (SubjectDTO subjectId : subjectList) {
                SubjectComboBox.addItem(subjectId.getSubjectID());
                
            }
        } catch (IOException ex) {
            Logger.getLogger(AddTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

