/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.gdse43.dao.db.DBConnection;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DEll
 */
public class Reports extends javax.swing.JPanel {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLogin3 = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registration Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 220, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Payments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 220, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Student Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 220, 50));

        btnLogin3.setBackground(new java.awt.Color(0, 0, 204));
        btnLogin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Exam Results");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });
        add(btnLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 220, 50));

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/animated-ppt-background-29.jpg"))); // NOI18N
        add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -5, 910, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/edu/ijse/Jasper/MonthlyPayment.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
        } catch (JRException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/edu/ijse/Jasper/ExamDetails.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
            /* try {
                JasperUtil.init(ExamForm.class);

                JasperReportsContext ctx=JasperUtil.getReportContext();

                JasperReport compileReport=JasperUtil.getCompiledReport("ExamDetails.jasper");

                JasperFillManager filManager=JasperFillManager.getInstance(ctx);

                HashMap<String,Object>reportParams=new HashMap<>();

                //reportParams.put("name",cmbSelectSupplier.getSelectedItem().toString());

                //System.out.println(cmbSelectSupplier.getSelectedItem().toString());

                Connection conn=DBConnection.getInstance().getConnection();

                JasperPrint filledReport=filManager.fill(compileReport, reportParams,conn);

                IJSEJasperViewer frmJSEJasperViewer=new IJSEJasperViewer(filledReport);
                frmJSEJasperViewer.setSize(1200, 650);
                frmJSEJasperViewer.setTitle("Exam details....!");
                frmJSEJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
                frmJSEJasperViewer.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(ExamForm
                    .class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        } catch (JRException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLogin3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/edu/ijse/Jasper/StudentDetails.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
        } catch (JRException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            JasperReport compiledReport = (JasperReport) JRLoader.loadObject(Reports.class.getResourceAsStream("/edu/ijse/Jasper/RegistrationFees.jasper"));
            Connection conn = DBConnection.getInstance().getConnection();
            HashMap<String, Object> reportParms = new HashMap<>();
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport, reportParms, conn);
            JasperViewer.viewReport(filledReport);
        } catch (JRException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
