/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.core.dto.BatchDTO;
import edu.ijse.gdse43.core.dto.SheduleDTO;
import edu.ijse.gdse43.core.dto.SubjectDTO;
import edu.ijse.gdse43.core.dto.TeacherDTO;
import edu.ijse.gdse43.custom.controller.BatchController;
import edu.ijse.gdse43.custom.controller.SheduleController;
import edu.ijse.gdse43.custom.controller.SubjectController;
import edu.ijse.gdse43.custom.controller.TeacherController;
import edu.ijse.gdse43.util.Validation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEll
 */
public class ScheduleForm extends javax.swing.JFrame {

    /**
     * Creates new form SheduleForm
     */
    public ScheduleForm() throws Exception {
        initComponents();
        loadSystemDate();
        loadSystemTime();
        loadBatchIDs();
        loadTeacherIDs();
        loadSubjectIDs();
        loadSheduleID();
        txtSheduleID.setEditable(false);

        //btnViewActionPerformed(null);
        tblShedule.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    // if (tblShedule.getSelectedRow() = -1) return;
                    String startTime = shComboBox.getSelectedItem() + ":" + smComboBox.getSelectedItem() + ":00";
                    String endTime = ehComboBox.getSelectedItem() + ":" + emComboBox.getSelectedItem() + ":00";
                    txtSheduleID.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 0).toString());
                    String batch= tblShedule.getValueAt(tblShedule.getSelectedRow(), 1).toString();
                    String teacher=tblShedule.getValueAt(tblShedule.getSelectedRow(), 2).toString();
                    String id = tblShedule.getValueAt(tblShedule.getSelectedRow(), 3).toString();
                    txtDate.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 4).toString());
                    startTime = (tblShedule.getValueAt(tblShedule.getSelectedRow(), 5).toString());
                    endTime=(tblShedule.getValueAt(tblShedule.getSelectedRow(), 6).toString());

                    String subName = SheduleController.searchNameById(id);
                    String batchName=SheduleController.searchBatchNo(batch);
                    String teacherName=SheduleController.searchTeacherName(teacher);

                    SubjectIDComboBox.setSelectedItem(subName);
                    BatchIDComboBox.setSelectedItem(batch);
                    TeacherIDComboBox.setSelectedItem(batch);
                    
                } catch (Exception ex) {
                    Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                

            }

           

           
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        ButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TitleLabel = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShedule = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        TeacherIDComboBox = new javax.swing.JComboBox();
        SubjectIDComboBox = new javax.swing.JComboBox();
        BatchIDComboBox = new javax.swing.JComboBox();
        txtSheduleID = new javax.swing.JTextField();
        DateChooser = new com.toedter.calendar.JDateChooser();
        smComboBox = new javax.swing.JComboBox();
        shComboBox = new javax.swing.JComboBox();
        ehComboBox = new javax.swing.JComboBox();
        emComboBox = new javax.swing.JComboBox();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time");
        ButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home-icon.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 84, 85));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 800));

        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Actions-window-close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        TitlePanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 60, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TitlePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 10, 60, 60));

        TitleLabel.setBackground(new java.awt.Color(0, 0, 153));
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/if_graduated_44907.png"))); // NOI18N
        TitleLabel.setText("          RASANYA  INSTITUTE");
        TitleLabel.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        TitleLabel.setOpaque(true);
        TitlePanel.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 130));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jXLabel1.setText("                                     SCHEDULE");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXLabel1.setOpaque(true);
        jPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));

        jXLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel9.setText("Shedule ID");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 113, 25));

        jXLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel10.setText("Batch ID");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 113, 25));

        jXLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel11.setText("Subject Name");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 113, 25));

        jXLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel12.setText("Teacher ID");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 113, 25));

        jXLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel13.setText("Date");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 113, 25));

        jXLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel14.setText("End Time");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 113, 25));

        btnCancel.setBackground(new java.awt.Color(0, 0, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 100, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 392, 910, 10));

        btnAdd.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 100, 40));

        btnEdit.setBackground(new java.awt.Color(0, 0, 102));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 100, 40));

        jXLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel15.setText("Strat Time");
        jXLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jXLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 113, 25));

        tblShedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SheduleID", "Batch ID", "Teacher ID", "Subject ID", "Date", "Strat Time", "End Time"
            }
        ));
        tblShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShedule);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 810, 110));

        btnView.setBackground(new java.awt.Color(0, 0, 102));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 100, 40));

        jPanel1.add(TeacherIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 150, 20));

        SubjectIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectIDComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(SubjectIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, 20));

        jPanel1.add(BatchIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 20));
        jPanel1.add(txtSheduleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, -1));

        DateChooser.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 20));

        smComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45", "60" }));
        smComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(smComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 60, 20));

        shComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7", "8", "9", "10", "11", "12", "1", "2", "3", " " }));
        jPanel1.add(shComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 60, 20));

        ehComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11", "12", "1", "2", "3", "4", "5" }));
        jPanel1.add(ehComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 60, 20));

        emComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45", "60" }));
        jPanel1.add(emComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 910, 670));

        setSize(new java.awt.Dimension(1100, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            

            SubjectIDComboBox.requestFocus();
        } else if (response == 1) {

        } else if (response == 2) {

        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        Date date = DateChooser.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String format = dateFormat.format(date);

        try {
            String subject = SubjectIDComboBox.getSelectedItem().toString();
            SubjectDTO SubjectName = SubjectController.searchSubjectName(subject);
            String teacher=TeacherIDComboBox.getSelectedItem().toString();
            String teacherName=SheduleController.searchTeacherIdByName(teacher);
            System.out.println("T"+teacherName);
            String batch=BatchIDComboBox.getSelectedItem().toString();
            String batchName=SheduleController.searchBatchIdByName(batch);
            System.out.println("B"+batchName);
            String startTime = shComboBox.getSelectedItem() + ":" + smComboBox.getSelectedItem() + ":00";
            String endTime = ehComboBox.getSelectedItem() + ":" + emComboBox.getSelectedItem() + ":00";
            SheduleDTO shedule = new SheduleDTO(
                    txtSheduleID.getText(),
                    batchName,
                    teacherName,
                    SubjectName.getSubjectID(),
                    format,
                    // txtSheduleDate.getText(),
                    startTime,
                    endTime);
            boolean result = SheduleController.addShedule(shedule);

            if (result) {
                String id = txtSheduleID.getText();
                if (id.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter a ID");
                    txtSheduleID.selectAll();
                    txtSheduleID.requestFocusInWindow();
                    return;
                }

                /*if (date.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Please enter a date");
                 txtSheduleDate.selectAll();
                 txtSheduleDate.requestFocusInWindow();
                 return;
                 }*/
               
                

                JOptionPane.showMessageDialog(this, "Shedule has been successfully Added");
                txtSheduleID.setText("");
                
                
                BatchIDComboBox.requestFocusInWindow();
                try {
                    txtSheduleID.setText(IdGenarator.getNewID("Shedule", "SheduleID", "H"));
                } catch (IOException ex) {
                    Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            String startTime = shComboBox.getSelectedItem() + ":" + smComboBox.getSelectedItem() + ":00";
            String endTime = ehComboBox.getSelectedItem() + ":" + emComboBox.getSelectedItem() + ":00";
            SheduleDTO shedule = new SheduleDTO(
                    txtSheduleID.getText(),
                    BatchIDComboBox.getSelectedItem().toString(),
                    TeacherIDComboBox.getSelectedItem().toString(),
                    SubjectIDComboBox.getSelectedItem().toString(),
                    txtDate.getText(),
                    startTime,
                    endTime);

            boolean result = SheduleController.updateShedule(shedule);
            if (result) {
                JOptionPane.showMessageDialog(this, "Succesfully Updated");
            }
        } catch (Exception ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        try {

            ArrayList<SheduleDTO> alShedules = SheduleController.getAllShedules();
            DefaultTableModel dtm = (DefaultTableModel) tblShedule.getModel();
            dtm.setRowCount(0);
            for (SheduleDTO shedule : alShedules) {
                Object[] rowData = {shedule.getSheduleID(),
                    shedule.getBatchID(),
                    shedule.getTeacherID(),
                    shedule.getSubjectID(),
                    shedule.getDate(),
                    shedule.getStartTime(),
                    shedule.getEndTime()
                };

                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnViewActionPerformed

    private void SubjectIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectIDComboBoxActionPerformed
        txtDate.requestFocus();
    }//GEN-LAST:event_SubjectIDComboBoxActionPerformed

    private void tblSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSheduleMouseClicked
        /*  txtSheduleID.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 0).toString());
         BatchIDComboBox.setSelectedItem(tblShedule.getValueAt(tblShedule.getSelectedRow(), 1).toString());
         TeacherIDComboBox.setSelectedItem(tblShedule.getValueAt(tblShedule.getSelectedRow(), 2).toString());
         String subject=(tblShedule.getValueAt(tblShedule.getSelectedRow(), 3).toString());
         try {
         SubjectDTO searchSubjectName = SubjectController.searchSubjectName(subject);
         System.out.println(searchSubjectName.getSubjectName());
         System.out.println("erfgw");
         SubjectIDComboBox.addItem(searchSubjectName.getSubjectName());
         } catch (Exception ex) {
         Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
         }
         txtDate.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 4).toString());
         txtStartTime.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 5).toString());
         txtEndTime.setText(tblShedule.getValueAt(tblShedule.getSelectedRow(), 6).toString());*/
    }//GEN-LAST:event_tblSheduleMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to exit");
        if (response == 0) {
            System.exit(0);
        } else if (response == 1) {
        } else if (response == 2) {

        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void smComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ScheduleForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BatchIDComboBox;
    private javax.swing.JPanel ButtonPanel;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox SubjectIDComboBox;
    private javax.swing.JComboBox TeacherIDComboBox;
    private org.jdesktop.swingx.JXLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox ehComboBox;
    private javax.swing.JComboBox emComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private javax.swing.JComboBox shComboBox;
    private javax.swing.JComboBox smComboBox;
    private javax.swing.JTable tblShedule;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSheduleID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String FormatDate = df.format(d1);
        txtDate.setText(FormatDate);

    }

    private void loadSystemTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String FormatDate = df.format(d1);
                txtTime.setText(FormatDate);
            }
        }).start();
    }

    private void loadBatchIDs() throws Exception {
        ArrayList<BatchDTO> batchList = BatchController.getAllBatches();
        for (BatchDTO batchId : batchList) {
            BatchIDComboBox.addItem(batchId.getBatchNo());

        }
    }

    private void loadTeacherIDs() throws Exception {
        ArrayList<TeacherDTO> teacherList = TeacherController.getAllTeachers();
        for (TeacherDTO teacherId : teacherList) {
            TeacherIDComboBox.addItem(teacherId.getName());

        }
    }

    private void loadSubjectIDs() {
        try {
            ArrayList<SubjectDTO> subjectList = SubjectController.getAllSubjects();
            for (SubjectDTO subjectID : subjectList) {
                SubjectIDComboBox.addItem(subjectID.getSubjectName());

            }
        } catch (Exception ex) {
        }
    }

    private void loadSheduleID() {
        try {
            txtSheduleID.setText(IdGenarator.getNewID("Shedule", "SheduleID", "H"));
        } catch (IOException ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /* private void minDate(Date date) {
     Calendar calendar=Calendar.getInstance();
     calendar.add(Calendar.DATE, -1);
     DateChooser.setMinSelectableDate(date);
     txtSheduleDate.setText(DateChooser.getT);
        
     }*/
}
