/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.custom.controller.TeacherController;
import static edu.ijse.gdse43.view.AddTeacherForm.txtTeacherID;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DEll
 */
public class TeacherForm extends javax.swing.JFrame {

    /**
     * Creates new form TeacherForm
     */
    public TeacherForm() {
        initComponents();
        loadSystemDate();
        loadSystemTime();
        MainPanel.setVisible(true);
        ButtonPanel.setVisible(true);
        TitlePanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnAddTeacher = new javax.swing.JButton();
        btnUpadeteTeacher = new javax.swing.JButton();
        btnViewTeacher = new javax.swing.JButton();
        btnDeleteTeacher = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TitleLabel = new org.jdesktop.swingx.JXLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home-icon.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 84, 85));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time");
        ButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        ButtonPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        btnAddTeacher.setBackground(new java.awt.Color(0, 51, 153));
        btnAddTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Circle-add-icon.png"))); // NOI18N
        btnAddTeacher.setText("Add ");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 50));

        btnUpadeteTeacher.setBackground(new java.awt.Color(0, 51, 153));
        btnUpadeteTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpadeteTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnUpadeteTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Edit Property_48px.png"))); // NOI18N
        btnUpadeteTeacher.setText("Edit  ");
        btnUpadeteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpadeteTeacherActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnUpadeteTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 380, 190, 50));

        btnViewTeacher.setBackground(new java.awt.Color(0, 51, 153));
        btnViewTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Search_48px.png"))); // NOI18N
        btnViewTeacher.setText("View ");
        btnViewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacherActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnViewTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, 50));

        btnDeleteTeacher.setBackground(new java.awt.Color(0, 51, 153));
        btnDeleteTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Empty Trash_48px.png"))); // NOI18N
        btnDeleteTeacher.setText("Remove");
        btnDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeacherActionPerformed(evt);
            }
        });
        ButtonPanel.add(btnDeleteTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 50));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Actions-window-close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        TitlePanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 60, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TitlePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 60, 60));

        TitleLabel.setBackground(new java.awt.Color(0, 0, 153));
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/if_graduated_44907.png"))); // NOI18N
        TitleLabel.setText("          RASANYA  INSTITUTE");
        TitleLabel.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        TitleLabel.setOpaque(true);
        TitlePanel.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 130));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBorder(new org.jdesktop.swingx.border.IconBorder());
        MainPanel.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/chemical-in-a-conical-flask-525389003-5898d7753df78caebca717b3.jpg"))); // NOI18N
        MainPanel.add(jLabel4);

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 910, 670));

        setSize(new java.awt.Dimension(1100, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed

        
        try {
            AddTeacherForm t1 = new AddTeacherForm();
            MainPanel.removeAll();
            MainPanel.add(t1);
            MainPanel.repaint();
            MainPanel.revalidate();
            MainPanel.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            


    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnUpadeteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpadeteTeacherActionPerformed
        try {
            UpdateTeacherForm t3 = new UpdateTeacherForm();
            MainPanel.removeAll();
            MainPanel.add(t3);
            MainPanel.repaint();
            MainPanel.revalidate();
            MainPanel.setVisible(true);// TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpadeteTeacherActionPerformed

    private void btnViewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacherActionPerformed
        try {
            ViewTeacherForm t4 = new ViewTeacherForm();
            MainPanel.removeAll();
            MainPanel.add(t4);
            MainPanel.repaint();
            MainPanel.revalidate();
            MainPanel.setVisible(true); // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewTeacherActionPerformed

    private void btnDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeacherActionPerformed
        try {
            DeleteTeacherForm t2 = new DeleteTeacherForm();
            MainPanel.removeAll();
            MainPanel.add(t2);
            MainPanel.repaint();
            MainPanel.revalidate();
            MainPanel.setVisible(true);  
           // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TeacherForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDeleteTeacherActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       int response=JOptionPane.showConfirmDialog(this,"Are you sure want to exit");
       if(response==0){
       System.exit(0);
       }else if(response==1){
       }else if(response==2){
           
       }
       

    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MainPanel;
    private org.jdesktop.swingx.JXLabel TitleLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteTeacher;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUpadeteTeacher;
    private javax.swing.JButton btnViewTeacher;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadSystemDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String DateFormat = df.format(d1);
        txtDate.setText(DateFormat);
    }

    private void loadSystemTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Date d1 = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String DateFormat = df.format(d1);
                txtTime.setText(DateFormat);
            }
        }).start();
    }

   
    

}
