/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse43.view;

import edu.ijse.IdGenarater.IdGenarator;
import edu.ijse.gdse43.core.dto.RegistrationDTO;
import edu.ijse.gdse43.core.dto.StudentDTO;
import edu.ijse.gdse43.core.dto.SubjectDTO;
import edu.ijse.gdse43.custom.controller.RegistrationController;
import edu.ijse.gdse43.custom.controller.StudentController;
import edu.ijse.gdse43.custom.controller.SubjectController;
import static edu.ijse.gdse43.view.AddRegistrationForm.txtRegistrationID;
import static edu.ijse.gdse43.view.AddRegistrationForm.txtStudentID;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class UpdateStudentForm extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStudentForm
     */
    public UpdateStudentForm() {
        try {
            initComponents();
            loadStudentIds();
            loadRegistrationIds();
            loadSubjectIds();
            txtDOB.setEditable(false);
            txtRegistrationId.setEditable(false);
        } catch (Exception ex) {
            Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudentPanel = new javax.swing.JPanel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtSchool = new javax.swing.JTextField();
        txtRegistrationId = new javax.swing.JTextField();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXLabel19 = new org.jdesktop.swingx.JXLabel();
        jXLabel20 = new org.jdesktop.swingx.JXLabel();
        txtLName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jXLabel21 = new org.jdesktop.swingx.JXLabel();
        jXLabel24 = new org.jdesktop.swingx.JXLabel();
        btnClose = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        StudentIDComboBox = new javax.swing.JComboBox();
        txtFName = new javax.swing.JTextField();
        SubjectIDComboBox = new javax.swing.JComboBox();

        AddStudentPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel12.setText("Name of the School");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, 25));

        jXLabel1.setBackground(new java.awt.Color(255, 153, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255)));
        jXLabel1.setText("                         UPDATE  STUDENT");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddStudentPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));
        AddStudentPanel.add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 490, -1));
        AddStudentPanel.add(txtRegistrationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 230, -1));

        jXLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel14.setText("First Name");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 113, 25));

        jXLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel15.setText("Subject");
        jXLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 113, 25));

        jXLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel16.setText("Last Name");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 113, 25));

        jXLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel17.setText("Date of Birth");
        jXLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 113, 25));

        jXLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel18.setText("Phone");
        jXLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 113, 25));

        jXLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel19.setText("Address");
        jXLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 113, 25));

        jXLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel20.setText("National ID");
        jXLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 113, 25));
        AddStudentPanel.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 230, -1));
        AddStudentPanel.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, -1));
        AddStudentPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, -1));
        AddStudentPanel.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 490, -1));
        AddStudentPanel.add(txtNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 230, -1));
        AddStudentPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 910, 20));

        jXLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel21.setText("Student ID");
        jXLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 113, 25));

        jXLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jXLabel24.setText("Registration ID");
        jXLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddStudentPanel.add(jXLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 113, 25));

        btnClose.setBackground(new java.awt.Color(0, 0, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Cancel");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        AddStudentPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 100, 40));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnUpdateItemStateChanged(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        AddStudentPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 100, 40));

        StudentIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " " }));
        StudentIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StudentIDComboBoxItemStateChanged(evt);
            }
        });
        AddStudentPanel.add(StudentIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 220, 30));
        AddStudentPanel.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 230, -1));

        SubjectIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectIDComboBoxActionPerformed(evt);
            }
        });
        AddStudentPanel.add(SubjectIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String subject= SubjectIDComboBox.getSelectedItem().toString();
            SubjectDTO searchSubjectName = SubjectController.searchSubjectName(subject);
            
            
            StudentDTO student = new StudentDTO(
                    (String) StudentIDComboBox.getSelectedItem(),
                    txtRegistrationId.getText(),
                    txtFName.getText(),
                    txtLName.getText(),
                    txtDOB.getText(),
                    txtPhone.getText(),
                    txtAddress.getText(),
                    txtNID.getText(),
                    txtSchool.getText());
                    searchSubjectName.getSubjectID();
            boolean result = StudentController.updateStudent(student);

            String FName = txtRegistrationId.getText();

            if (FName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Student name");
                txtRegistrationId.selectAll();
                txtRegistrationId.requestFocusInWindow();
                return;
            }
            String LName = txtRegistrationId.getText();
            if (LName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Student name");
                txtLName.selectAll();
                txtLName.requestFocusInWindow();
                return;
            }

            String dob = txtDOB.getText();
            if (LName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a DOB");
                txtDOB.selectAll();
                txtDOB.requestFocusInWindow();
                return;
            }

            String Phone = txtPhone.getText();
            if (Phone.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Phone number");
                txtPhone.selectAll();
                txtPhone.requestFocusInWindow();
                return;
            }
            String Address = txtAddress.getText();

            if (Address.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Address");
                txtAddress.selectAll();
                txtAddress.requestFocusInWindow();
                return;
            }
            String NID = txtNID.getText();

            if (NID.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a NIC");
                txtNID.selectAll();
                txtNID.requestFocusInWindow();
                return;
            }
            String School = txtSchool.getText();

            if (School.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a School");
                txtSchool.selectAll();
                txtSchool.requestFocusInWindow();
                return;
            }

            String Registration = txtRegistrationID.getText();

            if (Registration.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a Registration");
                txtRegistrationID.selectAll();
                txtRegistrationID.requestFocusInWindow();
                return;
            }

            JOptionPane.showMessageDialog(this, "Student has been successfully Updated");
            txtStudentID.setText("");
            txtRegistrationId.setText("");
            txtLName.setText("");
            txtDOB.setText("");
            txtPhone.setText("");
            txtAddress.setText("");
            txtNID.setText("");
            txtSchool.setText("");
            txtRegistrationID.setText("");
            txtStudentID.setText(IdGenarator.getNewID("Student", "StudentID", "S"));
            txtRegistrationId.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to cancel");
        if (response == 0) {
            try {
                txtStudentID.setText("");
                txtRegistrationId.setText("");
                txtLName.setText("");
                txtDOB.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtNID.setText("");
                txtSchool.setText("");
                txtRegistrationID.setText("");
                txtStudentID.setText(IdGenarator.getNewID("Student", "StudentID", "S"));
                txtRegistrationId.requestFocus();
            } catch (IOException ex) {
                Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (response == 1) {

        } else if (response == 2) {

        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnUpdateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnUpdateItemStateChanged


    }//GEN-LAST:event_btnUpdateItemStateChanged

    private void StudentIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StudentIDComboBoxItemStateChanged
        try {
            String StudentID = (String) StudentIDComboBox.getSelectedItem().toString();
            StudentDTO student = null;
            student = StudentController.searchTeacher(StudentID);
            txtRegistrationId.setText(student.getRegistrationID());
            txtFName.setText(student.getFrstName());
            txtLName.setText(student.getLastName());
            txtDOB.setText(student.getDob());
            txtPhone.setText(student.getPhone());
            txtAddress.setText(student.getAddress());
            txtSchool.setText(student.getSchool());

        } catch (Exception ex) {
            Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
         String StudentID = (String) StudentIDComboBox.getSelectedItem().toString();
         StudentDTO student = null;
         student = StudentController.searchTeacher(StudentID);
         txtRegistrationID.setText(student.getRegistrationID());
         txtFName.setText(student.getFrstName());
         txtLName.setText(student.getLastName());
         txtDob.setText(student.getDob());
         txtPhone.setText(student.getPhone());
         txtAddress.setText(student.getAddress());
         txtBatchId.setText(student.getNic());
         txtSchool.setText(student.getSchool());
         */
    }//GEN-LAST:event_StudentIDComboBoxItemStateChanged

    private void SubjectIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectIDComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectIDComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JComboBox StudentIDComboBox;
    private javax.swing.JComboBox SubjectIDComboBox;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel19;
    private org.jdesktop.swingx.JXLabel jXLabel20;
    private org.jdesktop.swingx.JXLabel jXLabel21;
    private org.jdesktop.swingx.JXLabel jXLabel24;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRegistrationId;
    private javax.swing.JTextField txtSchool;
    // End of variables declaration//GEN-END:variables

    private void loadStudentIds() throws Exception {
        ArrayList<StudentDTO> studentList = StudentController.getAllStudents();
        for (StudentDTO studentId : studentList) {
            StudentIDComboBox.addItem(studentId.getStudentID());

        }
    }

    private void loadRegistrationIds() throws Exception {
        ArrayList<StudentDTO> studentList = StudentController.getAllStudents();
        for (StudentDTO studentId : studentList) {
            StudentIDComboBox.addItem(studentId.getStudentID());

        }
    }

    private void loadSubjectIds() {
        try {
            ArrayList<SubjectDTO> subjectList = SubjectController.getAllSubjects();
            for (SubjectDTO subjectId : subjectList) {
                SubjectIDComboBox.addItem(subjectId.getSubjectName());

            }
        } catch (Exception ex) {
            Logger.getLogger(UpdateStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
